---
- hosts: admin
  remote_user: root
  vars_files:
    - config/spryker_de.yaml
  tasks:
    - name: Prepare workspace
      import_tasks: subs/prepare_workspace.yaml
    - name: Prepare spryker
      import_tasks: subs/spryker_prepare.yaml
    - name: Setup spryker
      import_tasks: subs/spryker_setup.yaml
    - name: Finish it
      import_tasks: subs/spryker_postwork.yaml