---
- hosts: admin
  remote_user: root
  vars_files:
    - config/spryker_de.yaml
  tasks:
    - import_playbook: subs/prepare_workspace.yaml
    - import_playbook: subs/spryker_prepare.yaml
    - import_playbook: subs/spryker_setup.yaml
    - import_playbook: subs/spryker_postwork.yaml