---
- hosts: admin
  remote_user: root
  tasks:
    - vars_files:
      - config/config.yaml
    - include: subs/prepare_workspace.yaml
    - include: subs/spryker_prepare.yaml
    - include: subs/spryker_setup.yaml
    - include: subs/spryker_postwork.yaml