---
- name: Install spryker-composer
  composer:
    command: install
    working_dir: /data/shop/development/current
    no_dev: no
- name: Revoke postgre access
  command: psql -h database -p 5432 -U {{psqlusername}} -c "REVOKE CONNECT ON DATABASE {{psqldatabase}} FROM public" {{psqldatabase}}
- name: Install spryker
  command: "vendor/bin/install DE"
  args:
    chdir: /data/shop/development/current
  environment: "{{sprykerenv}}"